### ISSUE TITLE
Time in local time

### ISSUE THREAD

**Issue by MattD-FC** [badguy99/octoblock#8]
Hi, octoblock is great. Just what we needed to choose when to use electricity.

im struggling to get my wife using it because she cant be bothered deciphering the time (2020-06-03T13:30:00Z)

Is the any chance the code could be adjusted to show the date/time as June 3, 14:00 or similar?

Matt
<img width="502" alt="Screenshot 2020-06-03 at 21 53 20" src="https://user-images.githubusercontent.com/64532587/83688084-b8379b80-a5e4-11ea-9443-895687669e64.png">

**Comment by badguy99** [comment]
If you set `use_timezone` to `True` you'll get times showing GMT or BST:
![image](https://user-images.githubusercontent.com/61918526/83690359-8294b180-a5e8-11ea-8139-4563dc403763.png)

Otherwise I'd suggest either using a Markdown card, e.g.:
![image](https://user-images.githubusercontent.com/61918526/83692512-1156fd80-a5ec-11ea-917d-01e97041cf71.png)

Though doing that might be a bit of a pain, if you have lots to do and like the format of the entities cards. 
The other option is to do something similar with [template sensors](https://www.home-assistant.io/integrations/template/). 
In both cases if you switch to using timezone, you'll need to take care of matching BST or GMT suffixes. They are basically both taking the string, converting it to a datetime object and then back to a string in a different format.

ref. https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

**Comment by badguy99** [comment]
Closing this, as it can be done in HA as discussed above.

**Comment by MattD-FC** [comment]
Sorry for the slow reply. Many thanks for the detail above. Really helps. cheers
